// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const base = {
  'base.buttons.Next': 'Далее',

  'base.buttons.back': 'Назад',

  'categories.arcades': 'Аркады',

  'categories.casual': 'Казуальные',

  'categories.childish': 'Детские',

  'categories.desktop': 'Настольные',

  'categories.fighters': 'Боевики',

  'categories.forTwo': 'Для двоих',

  'categories.horror': 'Хорроры',

  'categories.popular': 'Популярные',

  'categories.puzzles': 'Головоломки',

  'categories.rolePlaying': 'Ролевые',

  'categories.simulators': 'Симуляторы',

  'categories.strategies': 'Стратегии',

  'categories.training': 'Обучающие',

  'components.molecules.Card.date': 'Дата публикации:',
  'components.molecules.Card.platform': 'Платформа:',
  'components.molecules.Card.views': 'Просмотров:',

  'components.molecules.Collapse.category': 'Категории',

  'components.molecules.Footer.agreement': 'Пользовательское соглашение',
  'components.molecules.Footer.confidentiality': 'Политика конфиденциальности',

  'components.organisms.Header.title': 'OIYN - ИГРОВОЙ ПОРТАЛ',

  'components.organisms.ListGames.noResults': 'Нет результатов',

  'components.organisms.forms.SearchForm.placeholder': 'Поисковик игр...',

  'components.routes.pages.Error404.title': 'OIYN',
  'components.routes.pages.Game.button': 'Играть',
  'components.routes.pages.Game.date': 'Дата публикации:',
  'components.routes.pages.Game.noResults': 'Нет результатов',
  'components.routes.pages.Game.platform': 'Платформа:',
  'components.routes.pages.Game.title': 'OIYN',
  'components.routes.pages.Game.views': 'Просмотров:',
  'components.routes.pages.Main.title': 'OIYN',
};
