// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/kz.po' and run '.po' extractor
export const base = {
  'base.buttons.Next': 'Siguiente',

  'base.buttons.back': 'Артқа',

  'categories.arcades': 'Аркадалар',

  'categories.casual': 'Кездейсоқ',

  'categories.childish': 'Балаларға арналған',

  'categories.desktop': 'Үстел үсті',

  'categories.fighters': 'Боевиктер',

  'categories.forTwo': 'Екі адамға арналған',

  'categories.horror': 'Хоррор',

  'categories.popular': 'Танымал',

  'categories.puzzles': 'Пазлдар',

  'categories.rolePlaying': 'Рөлдік ойындар',

  'categories.simulators': 'Симуляторлар',

  'categories.strategies': 'Стратегиялар',

  'categories.training': 'Тәрбиелік',

  'components.molecules.Card.date': 'Жарияланған күні:',
  'components.molecules.Card.platform': 'Платформа:',
  'components.molecules.Card.views': 'Көрсетілімдер:',

  'components.molecules.Collapse.category': 'Санаттар',

  'components.molecules.Footer.agreement': 'Қолданушы келісімі',
  'components.molecules.Footer.confidentiality': 'Құпиялылық саясаты',

  'components.organisms.Header.title': 'OIYN - ОЙЫН ПОРТАЛЫ',

  'components.organisms.ListGames.noResults': 'Нәтиже жоқ',

  'components.organisms.forms.SearchForm.placeholder': 'Ойын іздеуші...',

  'components.routes.pages.Error404.title': 'OIYN',
  'components.routes.pages.Game.button': 'Ойнау',
  'components.routes.pages.Game.date': 'Жарияланған күні:',
  'components.routes.pages.Game.noResults': 'Нәтиже жоқ',
  'components.routes.pages.Game.platform': 'Платформа:',
  'components.routes.pages.Game.title': 'OIYN',
  'components.routes.pages.Game.views': 'Көрсетілімдер:',
  'components.routes.pages.Main.title': 'OIYN',
};
